server:
    port: ${PORT}
spring:
  profiles: test
  datasource:
      driverClassName: org.postgresql.Driver
      url: ${DATABASE_JDBC_URL}
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
logging:
    config: classpath:logback-tomcat.xml