spring:
  profiles: local
  datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/iblog_local
      username: user
      password: user
  thymeleaf:
    cache: false
logging:
    config: classpath:logback-tomcat-local.xml