server:
    port: ${env.PORT}
spring:
  profiles: test
  datasource:
      driverClassName: org.postgresql.Driver
      url: ${env.DATABASE_JDBC_URL}
      username: ${env.DATABASE_USER}
      password: ${env.DATABASE_PASSWORD}
logging:
    config: classpath:logback-tomcat.xml